spring.application.name=spring-ai-test

spring.ai.dashscope.api-key=${DASHSCOPE-API-KEY}
spring.ai.dashscope.chat.options.model=deepseek-v4-pro

spring.ai.deepseek.api-key=${DEEPSEEK-API-KEY}
spring.ai.deepseek.chat.options.model=deepseek-v4-pro

logging.level.org.springframework.ai.chat=DEBUG