spring.application.name=spring-ai-test

spring.ai.dashscope.api-key=sk-b4ce18594d234b0b90cc249e793ff27f
spring.ai.dashscope.chat.options.model=deepseek-v4-pro

spring.ai.deepseek.api-key=sk-17818495777b452cb406cf110ac8dd4c
spring.ai.deepseek.chat.options.model=deepseek-v4-pro

logging.level.org.springframework.ai.chat=DEBUG